#!/usr/bin/env bash
# query DNS A records of a domain and its sub-domains

# default subdomains
DEFAULTS=("www" "lb-01" "web-01" "web-02")

query_dns () {
    if (( "$#" == 0 )) || (( "$#" > 2)); then
	echo "USAGE: ./0-world_wide_web DOMAIN SUBDOMAIN"
    elif (( "$#" == 1 )); then
	DOMAIN="$1"
	for val in "${DEFAULTS[@]}"; do
	    IP=$(dig A "${val}.${DOMAIN}" | awk '$1 ~ /^\w/ {print $5}')
	    echo "The subdomain $val is a A record and points to $IP"
	done
    elif (( "$#" == 2 )); then
	DOMAIN="$1"
	SUBDOMAIN="$2"
	IP=$(dig A "${SUBDOMAIN}.${DOMAIN}" | awk '$1 ~ /^\w/ {print $5}')
	echo "The subdomain $SUBDOMAIN is a A record and points to $IP"
    fi
}

query_dns "$@"
