#!/usr/bin/env bash
# transfers a file to a client to a server
# parameters:
# 1. the path to the file to be transferred
# 2. the IP of the server we want to transfer the file to
# 3. the username 'scp' connects with
# 4. the path of the ssh private key that 'scp' uses
# display 'Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY' if
# less than 3 parameters passed
# scp must transfer the file to the user home directory ~/
# strict host key checking must be disabled when using 'scp'

PATH_TO_FILE=""
IP=""
USERNAME=""
PATH_TO_SSH_KEY=""
DEST=""
SSH_OPTIONS="StrictHostKeyChecking no"

if [[ "$#" -eq 4 ]]; then
    PATH_TO_FILE="$1"
    IP="$2"
    USERNAME="$3"
    PATH_TO_SSH_KEY="$4"
    DEST="/home/$USERNAME"

    scp -i "$PATH_TO_SSH_KEY" -o "$SSH_OPTIONS" "$PATH_TO_FILE" \
	"$USERNAME"@"$IP":"$DEST"

else
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
