#!/usr/bin/env bash
# configure a Nginx server to have a custom web page that contains the string
# "Ceci n'est pas une page"
# the page must return an HTTP 404 error code

location1="\n\tlocation /redirect_me {\
\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\
\n\t}"

error="\n\terror_page 404 /404.html;"

config_folder="/etc/nginx/sites-available/"

apt update && apt install -y nginx
echo "Hello World!" > /var/www/html/index.html
printf "Ceci n'est pas une page\n\n" > /var/www/html/404.html

if cd $config_folder; then
    echo "changing working directory to $config_folder";
else
    "echo Failure";
    exit 1;
fi

if [[ -e "default.old" ]];then
    echo "default.old already exists";
else
    echo "creating default.old";
    mv default ./default.old;
fi

sed '/#/d' default.old | uniq -u | sed "\$ i\ $location1" > default
sed -i "\$ i\ $error" default
service nginx restart
