#!/usr/bin/env bash
# Display the content of the file /etc/password:
# username
# user id
# Home directory path for the user
f="/etc/passwd"
while read -r line; do
    echo "$line" | cut -d ':' -f1,3,6
done < $f
