#!/usr/bin/env bash
# groups visitors by IP and HTTP status code, and displays this data.
# OUTPUT FORMAT:
# OCCURENCE_NUMBER IP HTTP_CODE in list format
# Ordered from the greatest to the lowest number of occurrences
FILE="apache-access.log"
awk '{print $1 " " $9}' $FILE | sort -k1,2n | uniq -c | sort -g -r
