#!/usr/bin/env bash
# Display "Best School" 10 times and then "Hi" and"Best School"
# on 9th iteration.
i=1
while ((i <= 10)); do
    echo "Best School"
    if (( i == 9)); then
	echo "Hi"
    fi
    ((i++))
done
