#!/usr/bin/env bash
# Resolves localhost to 127.0.0.2 and facebook.com to 8.8.8.8
if [ ! -e /etc/hosts.bak ]; then
    cp /etc/hosts /etc/hosts.bak
fi
cp /etc/hosts.bak ~/hosts.new
sed -i 's/127.0.0.1/127.0.0.2/' ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
