#!/usr/bin/env bash
# Fix a container so that Nginx is running as the nginx user
pkill apache
sed -i -e '/^#user/ s/www-data/nginx/g' -e '/^#user/ s/#//g' /etc/nginx/nginx.conf
sed -i '/^#/! s/80/8080/g' /etc/nginx/sites-available/default
chown nginx /etc/nginx/nginx.conf
chmod u+r /etc/nginx/nginx.conf
sudo -u nginx service nginx start
